### ISSUE TITLE
hannali Podcast をはじめる

### ISSUE THREAD

**Issue by mazarimono** [hannari-python/hannali-DAO#4]
- [x] どうやるの？

**Comment by ksnt** [comment]
ポッドキャストを行うにはたくさんやり方はあるようですが、無料かつ簡単なものはこのAnchorというやつがよさそうですね。

https://anchor.fm/

複数人でのレコーディングは4人までの制限があるようです。
複数人で話すときのホストはラップトップではダメで、スマホからのみ可能のようす。リンクをシェアしてそこに来てもらえばよいっぽいです。

実際に録音してみましたが、まあ、録音キーを押すだけです笑。

Spotifyの製品なので、Spotifyで配信するのも簡単（？）かもです

**Comment by mazarimono** [comment]
簡単そうなので、これではじめてみましょうか！続けられそうなら、またいいのを考えるとかで！

**Comment by mazarimono** [comment]
とりあえず、各自セットアップして、ちょっと録音してみましょうか？

**Comment by mazarimono** [comment]
mtg で話したいこと

- [x] いつはじめる？
  - [x] 11月スタート
  - [x] 2週目, 3週目、の11月9日水曜、11月18日金曜日以外
  - [x] 21時から
- [x] スケジュール調整ツールが必要かな？
- [x] 何をネタにする？

**Comment by mazarimono** [comment]
はじめるめどがついたのでクローズ
